[book]
authors = ["Near Inc <hello@near.org>"]
multilingual = false
src = "specs"
title = "NEAR Protocol Specification"
description = "Specification of the NEAR Protocol"

[build]
build-dir = "docs"
use-default-preprocessors = false

[output.html]
git-repository-url = "https://github.com/near/NEPs/tree/master/specs"
mathjax-support = true
